name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: 'Do the build'
        run: yarn && yarn build
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist